from save_remaining import save
save(1,[
('57947','confirmed','Người áo xanh đi tới, cúi xuống đưa hai tay tới đầu người áo hồng; hai chân vẫn ở sàn. Không đặt chân lên vai như reasoning. Chi tiết xoa lưng đầu đoạn không được dùng để đếm vì có thể nhầm thời điểm.', [('places his feet on the woman’s shoulders','invented_event','contradicted',[8,9.4])]),
('33388','confirmed','Người ăn miếng thịt, đưa phần còn lại cho người áo trắng, sau đó mang hộp thức ăn ra; hộp mở chứa xương. Hộp được cầm nguyên vẹn chứ không bị đưa vào miệng nhai.', [('the man is chewing plastic','wrong_object','contradicted',[0,5]),('and finally a white container','invented_event','contradicted',[8,23.4])]),
('26027','ambiguous','Con ếch được cầm trên lòng bàn tay rồi nhấc dựng lên, xoay mặt bụng/lưng. Không thấy rõ sự rạch/tách lưng như model kể; chi tiết nhỏ bị tay che nên giữ chưa kết luận trước khi xem cận cảnh.', [('the frog’s back begins to split open','unsupported_specificity','ambiguous',[1.5,8.8])]),
('18290','confirmed','Nhiều người lần lượt nhảy từ vách đá, camera theo nhóm rơi xuống; không có một con gấu lớn chạy dọc vách. Reasoning biến nhóm người nhảy thành thú truy đuổi và người chạy trốn.', [('a large, dark animal—resembling a bear—leaping off the edge and charging down the rock face','invented_event','contradicted',[1.5,10.5])]),
('60501','ambiguous','Ba lính cứu hỏa ngồi cầm các vòi đỏ, có người đi qua, cuối clip tia nước quét sang người bên cạnh. Diễn biến phun nước có thật; trụ nước và cơ chế mất kiểm soát chưa xác minh, mốc chuyển phản ứng quá sớm.', [('a semi-circle around the hydrant','unsupported_specificity','ambiguous',[0,3.5])]),
('00418','confirmed','Cốc trong được chống bằng cây sào vàng sát trần hiên. Sau đó người đàn ông hạ sào, đưa tay lấy cốc. Model dựng nồi than nóng và cốc rơi chính xác vào cốc khác.', [('a pot of hot coals','wrong_object','contradicted',[0,10.5]),('the cup lands perfectly in the mug','invented_event','contradicted',[16,21.6])]),
('55777','ambiguous','Sư tử ở sau song sắt, người đưa tay vào rồi có giằng/giật tay và nhóm người cúi sát. Đoạn cuối bị đầu và áo người che; chưa xác minh được câu ngã lộn xuống đất.', [('tumble backward onto the ground','unsupported_specificity','ambiguous',[4.8,6.7])]),
('56580','ambiguous','Montage núi, người ngồi cúi đầu, đưa tay lên đầu rồi dang tay, trở lại cảnh núi. Chuỗi cảnh lớn đúng; chi tiết chắp tay cầu nguyện chưa xác minh, không coi ý nghĩa tâm lý là bịa.', [('hands clasped in prayer','unsupported_specificity','ambiguous',[8.5,13.5])]),
('59972','no_clear_error','Clip đen trắng với người lộn/xoay trước tường đá, cắt/hiệu ứng lặp, cuối logo MBGCORE. Nội dung nhìn thấy cơ bản khớp; không xác minh khả năng thể thao thực ngoài đời từ video biên tập.', []),
('23745','no_clear_error','Xe đen cắt/đỗ trước camera, người mở cửa bước ra chặn gần đầu xe, rồi camera đi tiếp qua bên cạnh. Model bỏ qua việc người xuất phát từ xe và đặt ranh giới giải nguy sớm; người chắn đường và vượt xe vẫn có thật.', [('the pedestrian stepping aside','temporal_misalignment','temporal_only',[11,13])]),
('02872','confirmed','Người thả vật vào cốc rồi lùi; một hiệu ứng xe xanh lao ngang cuốn người khỏi cảnh. Cốc bia vẫn trên bàn, không có cảnh bia phun từ miệng như model kể.', [('the beer erupts violently from the man’s mouth','invented_event','contradicted',[3.8,7.8])]),
('04884','no_clear_error','Các vũ công trong ánh sáng cam, nhiều góc/cắt, cuối hình lục giác. Các bằng chứng hình ảnh được nêu đều có cơ sở; đánh giá confusion không phải đối tượng audit đúng/sai cảm xúc.', []),
('51245','confirmed','Montage dơi trong bát, người cầm dơi, nhảy, tin tức. Chữ phủ là 会意字 / 會意字, không phải chữ dơi; model bịa nội dung dịch chữ. Không dùng montage này làm chứng cứ nguồn gốc dịch bệnh.', [('The character for bat means','wrong_attribute','contradicted',[0,4])]),
('10509','confirmed','Thợ lặn tiếp tục bơi/lặn vào vùng tối, bàn chân sáng và đám cặn/bọt vẫn nhìn thấy. Model kể một sinh vật có sừng ngoạm và nhấc người lên, trái với chuyển động người tự lặn xuống.', [('a massive, horned marine creature with glowing eyes that violently grabs the diver mid-swim','invented_event','contradicted',[16,21.7])]),
('00293','ambiguous','Chữ Friend đã có từ frame đầu, đầu bút đi dọc các chữ rồi cắt sang meme credits. Có thể đang chỉ/tracing thay vì viết; không kết luận sai chỉ từ nét bút mờ.', [('writing the word','unsupported_specificity','ambiguous',[0,8])]),
('56534','ambiguous','Hai người đứng gần giường tầng, cô gái đưa tay lên mặt chàng trai, sau đó chàng trai tạo dáng, chuyển đen trắng và phát lại. Phần chân nằm ngoài hình nên chưa xác minh được cô gái được hạ xuống đất.', [('is lowered to the ground','unsupported_specificity','ambiguous',[0,19.8])]),
])
