from save_remaining import save
save(2,[
('13014','ambiguous','Người chạy lấy gói đồ, trượt/ngã cạnh xe rồi có người áo sáng đuổi/giữ lại. Truy đuổi có thật; không xác định được người đuổi là cảnh sát từ trang phục thường.', [('the police officer','unsupported_specificity','ambiguous',[12,27])]),
('27239','no_clear_error','Chó chạy qua/rìa đường ray trước đầu tàu rồi chạy ra bên phải khi tàu tới. Reasoning đặt đoạn an toàn sớm và suy diễn lòng can đảm; không tính các lỗi thời gian/cảm xúc đó là bịa sự kiện.', [('is now safely off the tracks to the right','temporal_misalignment','temporal_only',[5.5,7])]),
('00304','confirmed','Người thi bikini đi giày đỏ trên sàn võ đài có dây bao quanh, ngã rồi quỳ tạo dáng. Model đổi võ đài thành phao bơm hơi; không dùng suy đoán cố tình ngã làm nhãn lỗi.', [('the inflatable ring','wrong_object','contradicted',[0,3])]),
('04466','confirmed','Người cầm cọ trang điểm quét lên mặt/ống kính, qua điểm che ống kính chuyển sang trang phục cướp biển. Không có dao nĩa ăn uống hay đầu mannequin rút từ tóc.', [('the fork and knife','wrong_object','contradicted',[0,6.8]),('he pulls a large, flexible mannequin head from his hair','invented_event','contradicted',[6,16.6])]),
('53460','no_clear_error','Xe máy đi chậm qua đàn bò trên đường, sau đó camera quay qua hồ và cây. Các cảnh chính có thật; mức confusion và lời bình mơ hồ không thuộc lỗi quan sát xác nhận.', []),
('05369','confirmed','Người áo xám đứng trên ván lướt cơ khí màu cam giữa đệm hơi xanh rồi ngã. Cuối clip cắt sang cửa kính/cửa hàng. Không có rượt đuổi trong sân vận động đông người.', [('a chaotic, high-speed chase through a crowded stadium','invented_event','contradicted',[4,10.5])]),
('24191','confirmed','Học sinh ngồi xếp tháp bằng nhiều lá bài nhỏ thành các ô tam giác, tháp đổ khoảng 6s. Không phải 10 cuốn sách; người bên phải vẫn ngồi, không thấy trận xô đẩy như model kể.', [('stacking 10 textbooks','wrong_object','contradicted',[0,6])]),
('07405','confirmed','Người áo đỏ cầm bóng trong lúc nhảy/lật ván trượt, đáp rồi chạy dẫn bóng qua người khác. Cuối đoạn ném về phía người giơ tay; không có cú úp bóng vào vành rổ như reasoning.', [('a breathtaking, high-flying slam dunk','invented_event','contradicted',[1.3,8.6])]),
('00386','confirmed','Meme quái vật mở cửa xen hình người cơ bắp ngồi trên giường có chăn/giấy và đầu giường. Model nói ngồi trên sàn. Phần reasoning 14.9–17s vượt quá frame cuối nguồn 14.83s, không coi khoảng ngoài clip là chứng cứ về sự kiện.', [('sitting on the floor','wrong_attribute','contradicted',[1.8,13])]),
('51648','confirmed','Nhân vật CGI có đầu nhãn cầu và thân ghép từ nhiều nhãn cầu nhỏ có con ngươi. Model gọi vật cấu tạo thân là quả mọng đông lạnh. Nhân vật đứng dậy, rồi hình thu nhỏ dần; không dùng cảm giác ghê sợ làm bằng chứng.', [('body made of frozen berries','wrong_object','contradicted',[0,6])]),
('51665','confirmed','Xe đỏ xuất hiện phía trước, xoay/ngang trên đường, xe gắn camera tiến qua để lại xe đỏ bên trái. Model đảo chủ thể vượt, kể xe đỏ tăng tốc vượt xe camera.', [('the car overtakes the camera vehicle','invented_event','contradicted',[13,16])]),
('55855','no_clear_error','Mèo vàng quẫy/ngọ nguậy ngay khe dưới cửa kính rồi chui/đi ra. Reasoning gọi là chơi đáng yêu và không xét khả năng mắc kẹt; ý định chơi/đau không đủ để xác nhận bịa, còn động tác và bối cảnh có thật.', []),
('00872','confirmed','Trẻ đội mũ xanh đi scooter về phía camera, mất thăng bằng ngã cạnh bãi xe rồi tự đứng lên. Người lớn ở phía sau đi bộ; không có người lao vào tấn công trẻ.', [('the man suddenly sprints into the frame','invented_event','contradicted',[1.5,3])]),
('00986','confirmed','Từ đầu là ghi màn hình quả địa cầu/bản đồ zoom tới Tokyo, cuối street view nhóm người đeo mặt nạ chim và quần áo khác màu. Model dựng bàn tay cầm cốc chỉ bản đồ.', [('a hand holding a cup','invented_event','contradicted',[0,10.5])]),
('08852','ambiguous','Montage cực nhanh anime, tai nạn xe, người ngã, bếp và meme. Reasoning gộp nhiều cảnh sai thời gian, chi tiết mặt phủ bọt/cửa sổ chưa xác minh; 2 fps có thể bỏ cảnh ngắn nên chưa gán lỗi xác nhận.', [('a person’s face covered in a white, foamy substance','unsupported_specificity','ambiguous',[5.5,18.5])]),
('05128','confirmed','Người đàn ông mở gói quà cạnh võ đài và rút ra ghế gấp đen rồi giơ ghế cười. Model kể lấy bút ký giấy; vật lớn được rút ra rõ là ghế.', [('he unexpectedly pulls out a pen and begins signing the paper','invented_event','contradicted',[5,11.5])]),
])
